 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */12 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: jasineri/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: Gunapathi
            # Text on contribution graph 
            text: Gunapathi S
       - uses: jasineri/simple-push-action@v1
